# Generated by Django 3.1.4 on 2020-12-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_cd_dvd_genre_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
